#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#spring:
#  application:
#    name: commodity-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/supermarket_online?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: FSD9di_dsG
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jpa:
#      hibernate:
#        ddl-auto: update
#      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#      show-sql: true
##  链路追踪
#  zipkin:
#    base-url: http://192.168.137.191:9411/
#    sleuth:
#      sampler:
#        probability: 0.5
#server:
#  port: 8081
##日志配置
#logging:
#  level:
##    可以指定具体包或者具体类的日志级别
#    org:
#      springframework:
#        cloud:
#          openfeign: debug
##  pattern:
##    console: "%d - %msg%n"
#  config: classpath:commodity-logback.xml
##输出到路径，不定义文件名
##  path: F:\loggingFile
##  输出到自定义文件名
##  file: F:\loggingFile\commodity-service.log
#env: dev