spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Zero9811/Supermarket-Online-Config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 7070
